id: P56BB02BD
initial_creation_type: input
source_metadata:
  title: Sarvamatasaṃgraha
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy
  data entry: Oliver Hellwig
  contribution to GRETIL: Oliver Hellwig
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:52:19.590300'
last_modified_at: '2022-03-09T14:52:19.590312'
